services:
  app:
    build:
      context: .
    image: ${IMAGE_NAME}
    ports:
      - "5000:${PORT}"
    environment:
      - PORT=${PORT}
      - DEEPSEEK_1=${DEEPSEEK_1}
      - OPEN_ROUTER_1=${OPEN_ROUTER_1}
      - OPENAI_1=${OPENAI_1}